trigger:
  - master
pr:
  - master
steps:
  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: '0.12.24'
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      commandOptions: '-backend=false'
  - task: TerraformCLI@0
    displayName: Validate Terraform
    inputs:
      command: 'validate'
      commandOptions: '-no-color'
  - script: terraform fmt -check=true
    displayName: Check Formatting